apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: cloudshop
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
