apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudshop
  name: backend-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rb
  namespace: cloudshop
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: cloudshop
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
